// Export pages
export '/pages/authentication/authentication_widget.dart'
    show AuthenticationWidget;
export '/pages/main_dashboard/main_dashboard_widget.dart'
    show MainDashboardWidget;
export '/pages/product_inventory/product_inventory_widget.dart'
    show ProductInventoryWidget;
export '/pages/sales_invoice_entry/sales_invoice_entry_widget.dart'
    show SalesInvoiceEntryWidget;
export '/pages/purchase_management/purchase_management_widget.dart'
    show PurchaseManagementWidget;
export '/pages/customer_ledger/customer_ledger_widget.dart'
    show CustomerLedgerWidget;
export '/pages/supplier_directory/supplier_directory_widget.dart'
    show SupplierDirectoryWidget;
export '/pages/finance_cash_book/finance_cash_book_widget.dart'
    show FinanceCashBookWidget;
export '/pages/analytics_reports/analytics_reports_widget.dart'
    show AnalyticsReportsWidget;
export '/pages/business_settings/business_settings_widget.dart'
    show BusinessSettingsWidget;
