default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"],
      duration: 1200,
      in_house: false
    )

    # Inject Team ID into ExportOptions.plist
    sh("sed -i '' 's/${APPLE_TEAM_ID}/#{ENV['TEAM_ID']}/g' ../ios/ExportOptions.plist")

    # Build from root directory
    sh("cd .. && flutter build ipa --release --export-options-plist=ios/ExportOptions.plist")

    upload_to_testflight(
      api_key: api_key,
      ipa: "../build/ios/ipa/*.ipa",
      skip_waiting_for_build_processing: true
    )
  end
end
