default_platform(:android)

platform :android do
  desc "Build release App Bundle"
  lane :build_aab do
    sh("flutter build appbundle --release")
  end

  desc "Upload to Play Store Internal track"
  lane :deploy_internal do
    build_aab
    upload_to_play_store(
      track: 'internal',
      aab: '../build/app/outputs/bundle/release/app-release.aab'
    )
  end
end
